Repository Tyrrrz/YoutubeExplode, pull requests merged in 2021-12, with the labels that each got.

#607 Ignore braces inside strings in `Json.Extract`
  YoutubeExplode/Utils/Json.cs
Labels: bug

#606 Fix age-restricted videos
  .gitignore
  YoutubeExplode.Tests/ChannelSpecs.cs
  YoutubeExplode.Tests/VideoSpecs.cs
  YoutubeExplode/Bridge/Extractors/PlayerResponseExtractor.cs
  YoutubeExplode/Bridge/Extractors/VideoWatchPageExtractor.cs
  YoutubeExplode/Bridge/YoutubeController.cs
  YoutubeExplode/Playlists/PlaylistVideo.cs
  YoutubeExplode/Videos/Streams/StreamClient.cs
Labels: bug, bug/caused by youtube

#610 Handle YouTube Shorts URLs in `VideoId`
  YoutubeExplode.Tests/VideoIdSpecs.cs
  YoutubeExplode/Videos/VideoId.cs
Labels: enhancement
